#!/usr/bin/env bash

THIS_BASENAME=$(basename "$0")
TMUX_SESSION_NAME=$THIS_BASENAME
HOSTS=""
USER=""
CERTIFICATE=""
FILENAME=""

syntax() {
	echo "Syntax: ${THIS_BASENAME} [-h|-u [user]|-c [path to certificate]|-sc [ssh-server-connect-string]|-ts [session-name]|-q|-f [filename]]"
	echo

	echo "-h | --help                                This help."
	echo

	echo "-u | --user                                User to use."
	echo

	echo "-c | --certificate                         Path to ssh-certificate to use."
	echo

	echo "-sc | --ssh-server-connect-string          SSH-connection-string, multiple."
	echo

	echo "-ts | --tmux-session-name                  Alternative tmux-session-name, default: ${THIS_BASENAME}"
	echo

	echo "-ns | --new-session                        Initializes a new session, like -ts [name]."
	echo

	echo "-q | --quiet                               Quiet-mode."
	echo

	echo "-f | --filename                            Filename of textfile to get -sc connection-strings from, line separated."
	echo

	echo "* Other arguments will be interpreted as '-sc'."
	echo

	echo "* For a maybe newer version of ${THIS_BASENAME} take a look on https://github.com/dennishafemann/tmux-cssh"
	echo
}

# Check if tmux is available
if [ $(which tmux) == "" ]; then
	echo "${THIS_BASENAME}"
	echo

	echo "TMUX is not avaiable."
	echo

	exit;
fi

# Walk through parameters
while [ $# -gt 0 ]; do
	case "$1" in
		-h|--help) syntax; exit;;
		-u|--user) USER="$2"; shift;;
		-c|--certificate) CERTIFICATE="$2"; shift;;
		-sc|--ssh-server-connect-string) HOSTS="${HOSTS} $2"; shift;;
		-ts|--tmux-session-name) TMUX_SESSION_NAME="$2"; shift;;
		-ns|--new-session) TMUX_SESSION_NAME="${TMUX_SESSION_NAME}_$(date +%s)";;
		-q|-quiet) QUIET="true";;
		-f|--filename) FILENAME="$FILENAME $2"; shift;;
		*) HOSTS="${HOSTS} $1";;
	esac

	shift
done

# Check if filenames with connection-strings are given
if [ "$FILENAME" != "" ]; then
	# Walk through all given filenames
	for filename in $FILENAME; do
		# Walk through all available connection strings
		while read connectionString; do
			# Add connection string to currently set hosts
			HOSTS="$HOSTS $connectionString"
		done < "${filename}"
	done
fi

# Check if tmux-session is available
if (( $(tmux ls 2> /dev/null | grep "${TMUX_SESSION_NAME}" | wc -l) > 0 )) ; then
	tmux attach -t "${TMUX_SESSION_NAME}"
	exit
fi


# Hosts available ?
if [ "${HOSTS}" == "" ]; then
	echo "* Hosts not given."
	echo

	syntax

	exit
fi

initTmuxCall="true"

# Walk through hosts
for host in ${HOSTS[@]}; do
	connectString="${host}"

	# Add user-part
	if [ "${USER}" != "" ]; then
		connectString="${USER}@${connectString}"
	fi

	# Add certificate-part
	if [ "${CERTIFICATE}" != "" ]; then
		connectString="-i ${CERTIFICATE} ${connectString}"
	fi

	# Finalize connect-string
	connectString="ssh ${connectString}"

	# Output
	if [ "${QUIET}" != "true" ]; then
		echo ${connectString}
	fi

	# First Call, inits the tmux-session
	if [ "${initTmuxCall}" == "true" ]; then
		tmux new-session -d -s "${TMUX_SESSION_NAME}" "${connectString}"

		initTmuxCall="false"
	# Attach zu tmux-session
	else
		tmux split-window -t "${TMUX_SESSION_NAME}" "${connectString}"
		tmux select-layout -t "${TMUX_SESSION_NAME}" tiled
	fi
done

# Set pane synchronisation
tmux set-window-option -t "${TMUX_SESSION_NAME}" synchronize-panes on

# Attach to tmux session
tmux attach-session -t "${TMUX_SESSION_NAME}"

